[build]
  base = "/"
  command = "npm config set registry https://registry.npmjs.org/ && npm install --legacy-peer-deps && npm run build"
  publish = "dist"
  functions = "functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-audit --no-fund"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.images]
  compress = true 
