[build]
  base = "/"
  command = "yarn install && yarn build"
  publish = "dist"
  functions = "functions"

[build.environment]
  NODE_VERSION = "18"
  YARN_VERSION = "1.22.19"
  YARN_FLAGS = "--no-ignore-optional --frozen-lockfile"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.images]
  compress = true 
