[build]
  command = "npm run build"
  publish = "dist"
  base = "/"
  functions = "functions"

[build.environment]
  NODE_VERSION = "18"
  YARN_VERSION = "1.22.19"
  YARN_FLAGS = "--no-ignore-optional --production=false"
  USE_NPM_INSTALL = "false"
  NPM_TOKEN = "false"
  CI = "true"
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.images]
  compress = true 
